import { createHash } from "node:crypto";
import type { LegalDocument, LegalLocale } from "../src/lib/legal-types";

export const LEGAL_VERSION = "2026-10-07.1";
export function buildLegalDocument(locale: LegalLocale, env: Record<string, string | undefined>): LegalDocument {
  const it = locale === "it-IT";
  const pick = (pt: string, italian: string) => it ? italian : pt;
  return {
    version: LEGAL_VERSION, locale, title: pick("Termos de uso e aviso de privacidade", "Condizioni d'uso e informativa privacy"),
    operator: {
      name: env.LEGAL_OPERATOR_NAME?.trim() || "",
      address: env.LEGAL_OPERATOR_ADDRESS?.trim() || "",
      country: env.LEGAL_OPERATOR_COUNTRY?.trim() || "",
      taxId: env.LEGAL_OPERATOR_TAX_ID?.trim() || "",
      email: "thetemplesale@gmail.com",
    },
    terms: [
      { title: pick("1. O que é o TempleSale", "1. Cos'è TempleSale"), body: pick(
        "TempleSale é uma plataforma de descoberta de empresas locais, com perfis comerciais, fotos, publicações, busca por proximidade e mapas. O contato pode continuar no WhatsApp ou em outro serviço externo. O site não realiza pagamentos nem é o vendedor dos produtos divulgados. A oferta, a venda, a entrega e os direitos do comprador devem ser esclarecidos pela empresa responsável.",
        "TempleSale è una piattaforma per scoprire attività locali attraverso profili commerciali, foto, pubblicazioni, ricerca di prossimità e mappe. Il contatto può proseguire su WhatsApp o altri servizi esterni. Il sito non gestisce pagamenti e non è il venditore dei prodotti pubblicizzati. Offerta, vendita, consegna e diritti dell'acquirente devono essere chiariti dall'attività responsabile.") },
      { title: pick("2. Conta e representação da empresa", "2. Account e rappresentanza dell'attività"), body: pick(
        "A conta comercial deve ser utilizada por uma pessoa maior de 18 anos com autorização para representar a empresa indicada. Informe dados verdadeiros e atualizados, proteja suas credenciais e comunique acessos indevidos. O nome e a empresa declarados no aceite não constituem verificação documental dos poderes de representação. O e-mail é confirmado pelo provedor de autenticação.",
        "L'account commerciale deve essere utilizzato da una persona maggiorenne autorizzata a rappresentare l'attività indicata. Fornisci dati veritieri e aggiornati, proteggi le credenziali e segnala accessi abusivi. Nome e attività dichiarati nell'accettazione non costituiscono verifica documentale dei poteri di rappresentanza. L'indirizzo email viene confermato dal fornitore di autenticazione.") },
      { title: pick("3. Publicações e direitos", "3. Pubblicazioni e diritti"), body: pick(
        "Publique apenas conteúdo que você possa legalmente utilizar, incluindo imagens, marcas e dados de terceiros. Descreva com clareza produtos, preços, condições, disponibilidade e restrições. Você mantém seus direitos sobre o conteúdo e permite ao TempleSale hospedá-lo, exibi-lo e adaptá-lo tecnicamente apenas para operar e divulgar a plataforma. Essa autorização termina quando o conteúdo é removido, ressalvados backups temporários e obrigações legais.",
        "Pubblica solo contenuti che puoi utilizzare legittimamente, comprese immagini, marchi e dati di terzi. Descrivi chiaramente prodotti, prezzi, condizioni, disponibilità e restrizioni. Conservi i tuoi diritti sui contenuti e autorizzi TempleSale a ospitarli, mostrarli e adattarli tecnicamente solo per gestire e promuovere la piattaforma. L'autorizzazione termina alla rimozione del contenuto, salvi backup temporanei e obblighi di legge.") },
      { title: pick("4. Condutas proibidas", "4. Condotte vietate"), body: pick(
        "A plataforma proíbe fraudes, falsificação de identidade, anúncios enganosos, produtos falsificados, conteúdo ilegal, exploração sexual, ameaças, assédio, discriminação, divulgação de dados privados sem autorização, spam e violação de direitos autorais. Também proíbe oferta de drogas ilícitas, armas, documentos, dados pessoais e produtos ou serviços cuja venda seja proibida. Produtos sujeitos a restrições, como bebidas alcoólicas, só podem ser divulgados por empresas legalmente autorizadas, sem direcionamento a menores e respeitando as regras aplicáveis. Não tente invadir, automatizar abusivamente ou prejudicar o site.",
        "La piattaforma vieta frodi, impersonificazione, annunci ingannevoli, contraffazioni, contenuti illegali, sfruttamento sessuale, minacce, molestie, discriminazione, diffusione non autorizzata di dati privati, spam e violazioni del diritto d'autore. Vieta inoltre offerte di droghe illecite, armi, documenti, dati personali e prodotti o servizi la cui vendita sia vietata. Prodotti soggetti a restrizioni, come bevande alcoliche, possono essere pubblicizzati solo da attività legalmente autorizzate, senza rivolgersi a minori e nel rispetto delle norme applicabili. Non tentare intrusioni, automazioni abusive o azioni dannose per il sito.") },
      { title: pick("5. Segurança, mapas e serviços externos", "5. Sicurezza, mappe e servizi esterni"), body: pick(
        "Confira a identidade da empresa, as condições da oferta e o endereço antes de negociar. Não compartilhe senhas, códigos ou dados bancários em comentários. Localizações, distâncias e trajetos podem conter imprecisões e não substituem sinalização, regras de trânsito ou avaliação pessoal. Links para WhatsApp, Google Maps e outros serviços ficam sujeitos às regras e à privacidade desses fornecedores. O uso do site não garante vendas, alcance ou disponibilidade ininterrupta.",
        "Verifica l'identità dell'attività, le condizioni dell'offerta e l'indirizzo prima di trattare. Non condividere password, codici o dati bancari nei commenti. Posizioni, distanze e percorsi possono essere imprecisi e non sostituiscono segnaletica, norme stradali o valutazione personale. I collegamenti a WhatsApp, Google Maps e altri servizi sono soggetti alle condizioni e alla privacy di tali fornitori. L'uso del sito non garantisce vendite, visibilità o disponibilità ininterrotta.") },
      { title: pick("6. Denúncias e moderação", "6. Segnalazioni e moderazione"), body: pick(
        "Para denunciar conteúdo ou contestar uma decisão, escreva ao contato abaixo indicando o perfil ou publicação, os fatos e os elementos relevantes, sem divulgar dados desnecessários. O TempleSale pode remover conteúdo ou restringir contas por infrações, riscos de segurança ou obrigação legal, de forma proporcional, informando o motivo quando possível e permitindo contestação por e-mail. Nenhuma cláusula exclui direitos obrigatórios ou responsabilidade que a lei não permita excluir.",
        "Per segnalare contenuti o contestare una decisione, scrivi al contatto indicato specificando profilo o pubblicazione, fatti ed elementi pertinenti, senza diffondere dati non necessari. TempleSale può rimuovere contenuti o limitare account per violazioni, rischi di sicurezza o obblighi legali, in modo proporzionato, comunicando il motivo ove possibile e consentendo contestazioni via email. Nessuna clausola esclude diritti inderogabili o responsabilità che la legge non consente di escludere.") },
      { title: pick("7. Aceite, recusa e alterações", "7. Accettazione, rifiuto e modifiche"), body: pick(
        "Ao marcar a declaração e clicar em Aceitar e confirmar, você manifesta sua concordância com esta versão dos termos em nome da empresa declarada. O sistema registra sua conta, e-mail verificado, nome declarado, empresa, data do servidor e cópia exata do documento. O comprovante é um registro de aceite eletrônico, não uma assinatura eletrônica qualificada. Se recusar, a sessão é encerrada, a conta não é apagada e as funções da conta ficam indisponíveis até o aceite. Alterações materiais exigem novo aceite; a versão anterior permanece no comprovante. Você pode solicitar encerramento da conta pelo contato informado.",
        "Selezionando la dichiarazione e premendo Accetta e conferma, esprimi il tuo accordo con questa versione delle condizioni per l'attività dichiarata. Il sistema registra account, email verificata, nome dichiarato, attività, data del server e copia esatta del documento. La ricevuta è un registro di accettazione elettronica, non una firma elettronica qualificata. Se rifiuti, la sessione termina, l'account non viene cancellato e le sue funzioni restano indisponibili fino all'accettazione. Modifiche sostanziali richiedono una nuova accettazione; la versione precedente resta nella ricevuta. Puoi richiedere la chiusura dell'account al contatto indicato.") },
    ],
    privacy: [
      { title: pick("Privacidade: dados e finalidades", "Privacy: dati e finalità"), body: pick(
        "Tratamos dados da conta e da empresa, e-mail, nome, fotos, publicações, comentários, interações, localização informada ou autorizada e dados técnicos de acesso, como IP e navegador. São usados para operar a conta, mostrar empresas próximas, publicar conteúdo, proteger o serviço e atender solicitações. Perfis comerciais e publicações são públicos; seu comprovante de aceite é privado. A localização do visitante é utilizada para proximidade e mapas, não é exibida como perfil público.",
        "Trattiamo dati dell'account e dell'attività, email, nome, foto, pubblicazioni, commenti, interazioni, posizione fornita o autorizzata e dati tecnici di accesso, come IP e browser. Servono per gestire l'account, mostrare attività vicine, pubblicare contenuti, proteggere il servizio e rispondere alle richieste. Profili commerciali e pubblicazioni sono pubblici; la ricevuta di accettazione è privata. La posizione del visitatore serve per prossimità e mappe e non viene mostrata come profilo pubblico.") },
      { title: pick("Bases legais e permissões", "Basi giuridiche e autorizzazioni"), body: pick(
        "O tratamento necessário à conta e às funções solicitadas se baseia na execução do serviço; obrigações legais se baseiam na legislação aplicável. Segurança, prevenção de abuso e defesa de direitos podem se basear em interesse legítimo, com avaliação dos direitos dos titulares. Permissões opcionais, como localização e câmera, são solicitadas separadamente e podem ser recusadas ou revogadas nas configurações do dispositivo. Este aceite não autoriza marketing nem constitui consentimento genérico para todo tratamento de dados.",
        "Il trattamento necessario all'account e alle funzioni richieste si basa sull'esecuzione del servizio; gli obblighi legali si basano sulla normativa applicabile. Sicurezza, prevenzione degli abusi e tutela dei diritti possono basarsi sul legittimo interesse, valutando i diritti degli interessati. Autorizzazioni facoltative, come posizione e fotocamera, sono richieste separatamente e possono essere rifiutate o revocate nelle impostazioni del dispositivo. Questa accettazione non autorizza marketing e non costituisce consenso generico a ogni trattamento di dati.") },
      { title: pick("Fornecedores e transferências", "Fornitori e trasferimenti"), body: pick(
        "Utilizamos fornecedores de autenticação (Auth0), hospedagem (Vercel e Render), banco de dados e imagens (Cloudinary). Mapas e trajetos utilizam fornecedores externos, incluindo OpenStreetMap e OSRM, que podem receber informações técnicas e coordenadas necessárias. Ao abrir WhatsApp ou Google Maps, esses serviços recebem os dados incluídos no link. Autoridades podem receber informações quando houver fundamento legal. Informações sobre países de tratamento e salvaguardas: ",
        "Utilizziamo fornitori di autenticazione (Auth0), hosting (Vercel e Render), database e immagini (Cloudinary). Mappe e percorsi usano fornitori esterni, inclusi OpenStreetMap e OSRM, che possono ricevere dati tecnici e coordinate necessarie. Aprendo WhatsApp o Google Maps, tali servizi ricevono i dati inclusi nel collegamento. Le autorità possono ricevere informazioni quando esiste una base giuridica. Informazioni sui paesi di trattamento e sulle garanzie: ") + (env.LEGAL_PRIVACY_TRANSFER_DETAILS?.trim() || pick("pendentes de confirmação pelo responsável.", "in attesa di conferma del titolare.")) },
      { title: pick("Conservação e seus direitos", "Conservazione e diritti"), body: pick(
        "Os dados são mantidos pelo tempo necessário à prestação do serviço, às obrigações legais e à defesa de direitos. Política de conservação: ",
        "I dati vengono conservati per il tempo necessario al servizio, agli obblighi legali e alla tutela dei diritti. Politica di conservazione: ") +
        (env.LEGAL_PRIVACY_RETENTION?.trim() || pick("pendente de definição pelo responsável.", "in attesa di definizione da parte del titolare.")) + " " + pick(
        "Você pode solicitar acesso, correção, exclusão, limitação, portabilidade e oposição, conforme aplicável, pelo e-mail informado. Quando o tratamento se basear em consentimento, é possível revogá-lo sem afetar o tratamento anterior. Você também pode reclamar à autoridade de proteção de dados competente, incluindo o Garante per la protezione dei dati personali na Itália. Cookies e armazenamento necessários mantêm a sessão e preferências; recursos opcionais que exijam consentimento devem ter escolha separada.",
        "Puoi richiedere accesso, rettifica, cancellazione, limitazione, portabilità e opposizione, ove applicabili, tramite l'email indicata. Quando il trattamento si basa sul consenso, puoi revocarlo senza pregiudicare il trattamento precedente. Puoi inoltre presentare reclamo all'autorità competente, incluso il Garante per la protezione dei dati personali in Italia. Cookie e archiviazione necessari mantengono sessione e preferenze; funzioni facoltative che richiedono consenso devono prevedere una scelta separata.") },
    ],
  };
}
export function hashLegalDocument(document: LegalDocument): string {
  return createHash("sha256").update(JSON.stringify(document)).digest("hex");
}
export function legalPublicationReady(env: Record<string, string | undefined>): boolean {
  return ["LEGAL_OPERATOR_NAME", "LEGAL_OPERATOR_ADDRESS", "LEGAL_OPERATOR_COUNTRY", "LEGAL_PRIVACY_TRANSFER_DETAILS", "LEGAL_PRIVACY_RETENTION"].every(key => Boolean(env[key]?.trim()));
}
